# Encuesta Origen Destino en Hogares de la Zona Metropolitana del Valle de México 2017
### [INEGI](https://www.inegi.org.mx/programas/eod/2017/)
***
La Encuesta se levantó durante el periodo del 23 de enero al 3 de marzo del 2017, y tiene como objetivo obtener información que permita conocer la movilidad actual de los habitantes de la ZMVM, respecto a sus características, motivo, duración, medios de transporte y horario de desplazamientos, entre otros aspectos de los viajes que realizan.

In [2]:
import pandas as pd

In [187]:
pd.set_option('display.max_colwidth', -1)
pd.set_option("display.max_rows", 101)

## Transporte

In [3]:
ttransporte = pd.read_csv("./eod_2017_csv/ttransporte_eod2017/conjunto_de_datos/ttransporte.csv")

In [4]:
ttransporte.shape

(890748, 18)

In [5]:
ttransporte.head()

,id_tra,id_via,p5_3,n_via,p5_14,p5_16,p5_16_1_1,p5_16_1_2,p5_16_2,p5_17_1c,p5_17_2c,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
0,3198,1810,2,2,14,2,0,5,NaN,NaN,NaN,3,120,59,20,1,2,55
1,3199,1811,1,1,2,3,0,25,6.0,NaN,NaN,3,120,59,20,1,2,38
2,3200,1811,1,1,5,2,0,40,NaN,15.0,48.0,3,120,59,20,1,2,38
3,3201,1811,1,1,14,1,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38
4,3202,1811,1,1,14,4,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38

In [6]:
diccionario_ttransporte = pd.read_csv("./eod_2017_csv/ttransporte_eod2017/diccionario_de_datos/diccionario_datos_ttransporte.csv")

### Preguntas sobre transporte

In [7]:
diccionario_ttransporte[["nombre_campo","catálogo"]]

,nombre_campo,catálogo
0,Identificador de transporte,NaN
1,Identificador de viaje,NaN
2,5.3 Día de viaje,p5_3
3,5.8 Número de viaje,NaN
4,5.14 Medio de transporte que utilizó,p5_14
5,5.16 ¿En qué orden los utilizó?,NaN
6,5.16.1. incluyendo el tiempo de espera y trasbordo ¿cuántas horas hizo en (respuesta de 5.14)?,NaN
7,5.16.1. incluyendo el tiempo de espera y trasbordo ¿cuántos minutos hizo en (respuesta de 5.14)?,NaN
8,5.16.2. ¿cuánto gastó en (respuesta de 5.14)?,NaN
9,Código de estación que subió,p5_17_1c
10,Código de estación que abandonó,p5_17_2c
11,estrato sociodemográfico,estrato
12,factor,NaN
13,unidad primaria de muestreo,NaN
14,estrato de diseño muestral,NaN
15,tamaño de localidad,tloc
16,sexo de la persona,sexo
17,edad de la persona,edad

In [8]:
cats = list(diccionario_ttransporte["catálogo"].dropna())
cats

['p5_3', 'p5_14', 'p5_17_1c', 'p5_17_2c', 'estrato', 'tloc', 'sexo', 'edad']

In [9]:
catalog_ttrasporte = {}
for cat in cats:
    catalog_ttrasporte[cat]= pd.read_csv(f"./eod_2017_csv/ttransporte_eod2017/catalogos/{cat}.csv")

In [10]:
catalog_ttrasporte["p5_3"]

   cve                                   descrip
0  1    Viaje realizado entre semana (Sección V)
1  2    Viaje realizado en sábado (Sección VI)


***
## Viaje

In [77]:
tviaje = pd.read_csv("./eod_2017_csv/tviaje_eod2017/conjunto_de_datos/tviaje.csv", encoding="UTF-8")

In [12]:
tviaje.shape

(531594, 82)

In [78]:
tviaje.head()

,id_via,id_soc,p5_3,n_via,p5_6,p5_7_6,p5_7_7,dto_origen,p5_9_1,p5_9_2,...,p5_27_6,p5_27_7,p5_27_8,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
0,2936,1268,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
1,2937,1268,1,2,3,16,9,16,14,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
2,2938,1268,2,1,1,15,9,2,17,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
3,2939,1268,2,2,7,15,9,2,23,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
4,2940,1269,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,22

In [85]:
diccionario_tviaje = pd.read_csv("./eod_2017_csv/tviaje_eod2017/diccionario_de_datos/diccionario_datos_tviaje.csv")

In [204]:
diccionario_tviaje.head()

,nombre_campo,longitud,tipo,nemónico,catálogo,rango_claves,col_name
0,Identificador de viaje,6,N,id_via,NaN,1-531594,viaje_id
1,Identificador de persona,6,N,id_soc,NaN,1-200117,persona_id
2,Pregunta 5.3 Clasificación del día de viaje,1,C,p5_3,p5_3,"1,2",dia_viaje
3,Pregunta 5.8 número de viaje,2,C,n_via,NaN,ene-14,num_viaje
4,Pregunta 5.6 ¿Qué tipo de lugar es el origen de su viaje?,2,C,p5_6,p5_6,"01-16,99",tipo_lugar_origen

### Preguntas sobre viajes

In [82]:
diccionario_tviaje[["nombre_campo","catálogo"]]

,nombre_campo,catálogo
0,Identificador de viaje,NaN
1,Identificador de persona,NaN
2,Pregunta 5.3 Clasificación del día de viaje,p5_3
3,Pregunta 5.8 número de viaje,NaN
4,Pregunta 5.6 ¿Qué tipo de lugar es el origen de su viaje?,p5_6
5,Pregunta 5.7 Por favor dígame el nombre del lugar y la dirección: mun. o delegación,p5_7_6
6,Pregunta 5.7 Por favor dígame el nombre del lugar y la dirección: entidad,p5_7_7
7,Pregunta 5.7 Por favor dígame el nombre del lugar y la dirección: distrito origen del viaje,dto_origen
8,Pregunta 5.9.¿A qué hora comenzó?,NaN
9,Pregunta 5.9.¿En qué minuto comenzó?,NaN
10,Pregunta 5.10 ¿A qué hora terminó?,NaN
11,Pregunta 5.10 ¿En qué minuto terminó?,NaN
12,Pregunta 5.11a ¿Qué tipo de lugar fue el destino de su viaje?,p5_11a
13,Pregunta 5.12 Por favor dígame el nombre del lugar y la dirección de destino (mun. o delegación),p5_12_6
14,Pregunta 5.12 Por favor dígame el nombre del lugar y la dirección de destino (entidad),p5_12_7
15,Pregunta 5.12 Por favor dígame el nombre del lugar y la dirección de destino (distrito),dto_dest
16,Pregunta 5.13 ¿Cuál fue el propósito del viaje?,p5_13
17,Pregunta 5.14 Dígame por favor sí utilizó 01 automóvil como medio de transporte,p5_14_01
18,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 01 Automóvil?,p5_15_01
19,Pregunta 5.14 Dígame por favor sí utilizó 02 Colectivo/Micro como medio de transporte,p5_14_02
20,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 02 Colectivo/Micro?,p5_15_02
21,Pregunta 5.14 Dígame por favor sí utilizó 03 Taxi (App internet) como medio de transporte,p5_14_03
22,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 03 Taxi (App internet)?,p5_15_03
23,"Pregunta 5.14 Dígame por favor sí utilizó 04 Taxi (sitio, calle u otro) como medio de transporte",p5_14_04
24,"Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 04 Taxi (sitio, calle u otro)?",p5_15_04
25,Pregunta 5.14 Dígame por favor sí utilizó 05 Metro como medio de transporte,p5_14_05
26,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 05 Metro?,p5_15_05
27,Pregunta 5.14 Dígame por favor sí utilizó 06 Autobús RTP o M1 como medio de transporte,p5_14_06
28,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 06 Autobús RTP o M1?,p5_15_06
29,Pregunta 5.14 Dígame por favor sí utilizó 07 Bicicleta como medio de transporte,p5_14_07
30,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 07 Bicicleta?,p5_15_07
31,Pregunta 5.14 Dígame por favor sí utilizó 08 Autobús como medio de transporte,p5_14_08
32,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 08 Autobús?,p5_15_08
33,Pregunta 5.14 Dígame por favor sí utilizó 09 Moto como medio de transporte,p5_14_09
34,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 09 Moto?,p5_15_09
35,Pregunta 5.14 Dígame por favor sí utilizó 10 Trolebús como medio de transporte,p5_14_10
36,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 10 Trolebús?,p5_15_10
37,Pregunta 5.14 Dígame por favor sí utilizó 11 Metrobús o Mexibús como medio de transporte,p5_14_11
38,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 11 Metrobús o Mexibús?,p5_15_11
39,Pregunta 5.14 Dígame por favor sí utilizó 12 Tren ligero como medio de transporte,p5_14_12
40,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 12 Tren ligero?,p5_15_12
41,Pregunta 5.14 Dígame por favor sí utilizó 13 Tren suburbano como medio de transporte,p5_14_13
42,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 13 Tren suburbano?,p5_15_13
43,Pregunta 5.14 Dígame por favor sí 14 Caminó en la calle como medio de transporte,p5_14_14
44,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces 14 Caminó en la calle?,p5_15_14
45,Pregunta 5.14 Dígame por favor sí utilizó 15 Mexicable como medio de transporte,p5_14_15
46,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 15 Mexicable?,p5_15_15
47,Pregunta 5.14 Dígame por favor sí utilizó 16 Bicitaxi como medio de transporte,p5_14_16
48,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 16 Bicitaxi?,p5_15_16
49,Pregunta 5.14 Dígame por favor sí utilizó 17 Mototaxi como medio de transporte,p5_14_17
50,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 17 Mototaxi?,p5_15_17
51,Pregunta 5.14 Dígame por favor sí utilizó 18 Transporte escolar como medio de transporte,p5_14_18
52,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 18 Transporte escolar?,p5_15_18
53,Pregunta 5.14 Dígame por favor sí utilizó 19 Transporte de personal como medio de transporte,p5_14_19
54,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 19 Transporte de personal?,p5_15_19
55,Pregunta 5.14 Dígame por favor sí utilizó 20 Otro medio de transporte,p5_14_20
56,Pregunta 5.15 Desde que inició hasta que llegó a su destino final ¿cuántas veces usó 20 Otro medio de transporte?,p5_15_20
57,Pregunta 5.18 ¿para llegar a su destino condujo?,p5_18
58,"Pregunta 5.19 al inicio del viaje, ¿cuántas personas iban en el vehículo incluyéndose usted?",p5_19
59,Pregunta 5.20 ¿dónde se estacionó?,p5_20
60,Pregunta 5.21 ¿cuánta horas se estacionó?,NaN
61,Pregunta 5.21 ¿cuántos minutos se estacionó?,NaN
62,Pregunta 5.22 ¿pagó por estacionarse?,p5_22
63,Pregunta 5.23 ¿cuánto pagó en total?,NaN
64,Pregunta 5.24 ¿usted pagó…,p5_24
65,Pregunta 5.25 el automóvil que manejó el (día de viajes) ¿qué holograma tiene?,p5_25
66,"Pregunta 5.26 durante su viaje, ¿cuántas paradas intermedias hizo menores a 10 minutos y sin pago adicional Pregunta por transporte?",p5_26
67,Pregunta 5.27 ¿las paradas intermedias fueron para llevar o recoger a alguien?,p5_27_1
68,Pregunta 5.27 ¿las paradas intermedias fueron para ir a la gasolinería?,p5_27_2
69,Pregunta 5.27 ¿las paradas intermedias fueron para ir a un cajero?,p5_27_3
70,Pregunta 5.27 ¿las paradas intermedias fueron para hacer una compra rápida?,p5_27_4
71,Pregunta 5.27 ¿las paradas intermedias fueron para convivencia breve?,p5_27_5
72,Pregunta 5.27 ¿las paradas intermedias fueron para descansar?,p5_27_6
73,Pregunta 5.27 ¿las paradas intermedias fueron para trámite rápido?,p5_27_7
74,Pregunta 5.27 ¿las paradas intermedias fueron para otro motivo?,p5_27_8
75,estrato sociodemográfico,estrato
76,factor,NaN
77,unidad primaria de muestreo,NaN
78,estrato de diseño muestral,NaN
79,tamaño de localidad,tloc
80,sexo de la persona,sexo
81,edad de la persona,edad

In [87]:
diccionario_tviaje.to_csv("./data/diccionario_tviaje.csv")

In [105]:
diccionario_tviaje.shape

(82, 7)

#### New column names added by hand

In [27]:
diccionario_tviaje = pd.read_csv("./data/diccionario_tviaje.csv").drop(columns="Unnamed: 0")
diccionario_tviaje.head()

,nombre_campo,longitud,tipo,nemónico,catálogo,rango_claves,col_name
0,Identificador de viaje,6,N,id_via,NaN,1-531594,viaje_id
1,Identificador de persona,6,N,id_soc,NaN,1-200117,persona_id
2,Pregunta 5.3 Clasificación del día de viaje,1,C,p5_3,p5_3,"1,2",dia_viaje
3,Pregunta 5.8 número de viaje,2,C,n_via,NaN,ene-14,num_viaje
4,Pregunta 5.6 ¿Qué tipo de lugar es el origen d...,2,C,p5_6,p5_6,"01-16,99",tipo_lugar_origen

### Create a dictionary with all transport catalogs

In [313]:
cats = list(diccionario_tviaje["catálogo"].dropna())
cats

['p5_3',
 'p5_6',
 'p5_7_6',
 'p5_7_7',
 'dto_origen',
 'p5_11a',
 'p5_12_6',
 'p5_12_7',
 'dto_dest',
 'p5_13',
 'p5_14_01',
 'p5_15_01',
 'p5_14_02',
 'p5_15_02',
 'p5_14_03',
 'p5_15_03',
 'p5_14_04',
 'p5_15_04',
 'p5_14_05',
 'p5_15_05',
 'p5_14_06',
 'p5_15_06',
 'p5_14_07',
 'p5_15_07',
 'p5_14_08',
 'p5_15_08',
 'p5_14_09',
 'p5_15_09',
 'p5_14_10',
 'p5_15_10',
 'p5_14_11',
 'p5_15_11',
 'p5_14_12',
 'p5_15_12',
 'p5_14_13',
 'p5_15_13',
 'p5_14_14',
 'p5_15_14',
 'p5_14_15',
 'p5_15_15',
 'p5_14_16',
 'p5_15_16',
 'p5_14_17',
 'p5_15_17',
 'p5_14_18',
 'p5_15_18',
 'p5_14_19',
 'p5_15_19',
 'p5_14_20',
 'p5_15_20',
 'p5_18',
 'p5_19',
 'p5_20',
 'p5_22',
 'p5_24',
 'p5_25',
 'p5_26',
 'p5_27_1',
 'p5_27_2',
 'p5_27_3',
 'p5_27_4',
 'p5_27_5',
 'p5_27_6',
 'p5_27_7',
 'p5_27_8',
 'estrato',
 'tloc',
 'sexo',
 'edad']

In [314]:
catalog_tviaje = {}

In [317]:
for cat in cats:
    catalog_tviaje[cat]= pd.read_csv(f"./eod_2017_csv/tviaje_eod2017/catalogos/{cat}.csv")
    catalog_tviaje[cat].drop_duplicates(keep = False, inplace = True)

In [318]:
catalog_tviaje["dto_dest"]

     cve                                     descrip
0    1    Centro Histórico
1    2    Buenavista-Reforma
2    3    Tlatelolco
3    4    Morelos
4    5    Moctezuma
7    7    Obrera
12   10   Vertiz Narvarte
15   12   Palacio de los Deportes
19   14   Portales
20   15   Del Valle
21   16   Chapultepec-Polanco
24   18   Tezozomoc
25   19   El Rosario
26   20   Industrial Vallejo
29   22   Cuautepec
30   23   Reclusorio Norte
31   24   Ticomán
32   25   Nueva Industrial Vallejo
33   26   Instituto Politécnico
34   27   Tepeyac
35   28   La Villa
36   29   Nueva Atzacoalco
37   30   San Felipe de Jesús
38   31   Deportivo los Galeana
39   32   Bondojito
42   34   Aeropuerto
45   36   Zaragoza
46   37   UPIICSA
49   39   UAM Iztapalapa
50   40   Escuadrón 201
51   41   Parque Cerro de la Estrella
52   42   Lomas Estrella
59   45   Culhuacán CTM
64   48   Pedregal de Santo Domingo
65   49   Xotepingo
72   53   Las Águilas
73   54   Santa Lucia
74   55   Molinos
75   56   Santa Fe
81   59   Cuajimalpa
82   60   San Lorenzo Acopilco
89   64   Villa Olimpica
92   66   San Pedro Martir
97   69   Noria
102  72   Tulyehualco
105  74   Tláhuac
106  75   Mixquic
107  76   Santa Catarina
110  78   Desarrollo Urbano Quetzalcoatl
111  79   Buenavista Iztapalapa
..   ..                     ...
183  139  TAD San Juan Ixhuatepec
184  140  Lázaro Cardenas-Lomas de Tepeolulco
185  141  Coacalco -cabecera-
186  142  Villa de las Flores-Héroes Coacalco
187  143  Potrero-La Laguna
190  145  U.H. de San Pablo de las Salinas
191  146  Guadalupe Victoria-Recursos Hidráulicos
192  147  San Cristóbal Ecatepec
193  148  La Presa-Tulpetlac
194  149  Teleférico Ecatepec
195  150  Parques Industriales Ecatepec
196  151  Villa de Guadalupe Xalostoc
197  152  Valle de Aragón
198  153  Bosques de Aragón
199  154  Granjas Independencia
200  155  Valle de Aragón 3ra Secc
201  156  CC Center Plazas-Nueva Aragón
202  157  Héroes de la Independencia-San Agustin
203  158  La Costeña-Olimpica Jajalpa
204  159  Jardines de Sta Clara-Super Plaza Ecatepec
205  160  Multiplaza Aragón-Cd Azteca
206  161  Jardines de Morelos
207  162  Central de Abastos Ecatepec
219  167  Tecámac -cabecera-
242  173  Nuevo AICM
243  174  Texcoco Centro-Chapingo
246  176  El Sol
247  177  Juárez Pantitlán-Mercado de Carne
248  178  Mercado Pirules
249  179  Ayuntamiento de Nezahualcóyotl
250  180  Benito Juárez
251  181  Metropolitana
252  182  La Perla
253  183  CC Plaza Neza
254  184  Parque Industrial Izcalli
255  185  San Lorenzo-Xochitenco
256  186  CC Patio Chimalhuacán-Barrio La Rosita
257  187  Barrio Labradores-Jardines Acuitlapilco
266  192  Valle de los Reyes
267  193  Metro La Paz-Los Reyes
270  195  Geovillas de Ayotla-Unión Antorchista
271  196  Ixtapaluca centro-Acozac
274  198  CC Sendero y Galerias Ixtapaluca
275  199  CC Sendero Valle de Chalco-Santiago
276  200  Alfredo Baranda
277  201  Xico
280  203  Chalco de Díaz Covarrubias
297  300  Tizayuca
298  888  Fuera de la ZMVM
299  999  Distrito no especificado dentro de la ZMVM

[128 rows x 2 columns]

In [20]:
catalog_tviaje["dto_dest"].nunique()

cve        196
descrip    196
dtype: int64

## Dataframe merge

In [403]:
viajes = tviaje
viajes.shape

(531594, 82)

In [404]:
ignore = ['edad', 'p5_15_01', 'p5_15_02', 'p5_15_03', 'p5_15_04', 'p5_15_05', 'p5_15_06', 'p5_15_07',
         'p5_15_08', 'p5_15_09', 'p5_15_10', 'p5_15_11', 'p5_15_12', 'p5_15_13', 'p5_15_14', 'p5_15_15',
         'p5_15_16', 'p5_15_17', 'p5_15_18', 'p5_15_19', 'p5_15_20', 'p5_19', 'p5_26']

In [405]:
viajes.head(5)

,id_via,id_soc,p5_3,n_via,p5_6,p5_7_6,p5_7_7,dto_origen,p5_9_1,p5_9_2,...,p5_27_6,p5_27_7,p5_27_8,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
0,2936,1268,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
1,2937,1268,1,2,3,16,9,16,14,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
2,2938,1268,2,1,1,15,9,2,17,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
3,2939,1268,2,2,7,15,9,2,23,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
4,2940,1269,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,22

In [406]:
viajes.columns

Index(['id_via', 'id_soc', 'p5_3', 'n_via', 'p5_6', 'p5_7_6', 'p5_7_7',
       'dto_origen', 'p5_9_1', 'p5_9_2', 'p5_10_1', 'p5_10_2', 'p5_11a',
       'p5_12_6', 'p5_12_7', 'dto_dest', 'p5_13', 'p5_14_01', 'p5_15_01',
       'p5_14_02', 'p5_15_02', 'p5_14_03', 'p5_15_03', 'p5_14_04', 'p5_15_04',
       'p5_14_05', 'p5_15_05', 'p5_14_06', 'p5_15_06', 'p5_14_07', 'p5_15_07',
       'p5_14_08', 'p5_15_08', 'p5_14_09', 'p5_15_09', 'p5_14_10', 'p5_15_10',
       'p5_14_11', 'p5_15_11', 'p5_14_12', 'p5_15_12', 'p5_14_13', 'p5_15_13',
       'p5_14_14', 'p5_15_14', 'p5_14_15', 'p5_15_15', 'p5_14_16', 'p5_15_16',
       'p5_14_17', 'p5_15_17', 'p5_14_18', 'p5_15_18', 'p5_14_19', 'p5_15_19',
       'p5_14_20', 'p5_15_20', 'p5_18', 'p5_19', 'p5_20', 'p5_21_1', 'p5_21_2',
       'p5_22', 'p5_23', 'p5_24', 'p5_25', 'p5_26', 'p5_27_1', 'p5_27_2',
       'p5_27_3', 'p5_27_4', 'p5_27_5', 'p5_27_6', 'p5_27_7', 'p5_27_8',
       'estrato', 'factor', 'upm_dis', 'est_dis', 'tloc', 'sexo', 'edad'],
      dtype='object')

In [407]:
for nemonico in list(viajes.columns):
    x = diccionario_tviaje.loc[diccionario_tviaje["nemónico"]==nemonico, ["col_name"]];
    col_name = x.iloc[0,0]
    if nemonico not in ignore:
        if nemonico in catalog_tviaje:
            catalog_selected = catalog_tviaje[nemonico]
    

            print(col_name)
            print(nemonico)
            print(catalog_selected.columns)
            if nemonico == "p5_7_6" or nemonico == "p5_12_6":
#                 viajes = viajes.merge(catalog_selected, how='left', left_on=nemonico, right_on='mun')
#                 viajes = viajes.drop(columns=['mun'])
                pass
            else:
                viajes = viajes.merge(catalog_selected, left_on=nemonico, right_on='cve', how='left')
                viajes = viajes.drop(columns=['cve', nemonico])
                viajes = viajes.rename(columns={'descrip': f"{col_name}"})
    
#   Rename all remaining columns
    viajes = viajes.rename(columns={nemonico:col_name})

dia_viaje
p5_3
Index(['cve', 'descrip'], dtype='object')
tipo_lugar_origen
p5_6
Index(['cve', 'descrip'], dtype='object')
delegacion_origen
p5_7_6
Index(['ent', 'mun', 'descrip'], dtype='object')
entidad_origen
p5_7_7
Index(['cve', 'descrip'], dtype='object')
distrito_origen
dto_origen
Index(['cve', 'descrip'], dtype='object')
tipo_lugar_destino
p5_11a
Index(['cve', 'descrip'], dtype='object')
delegacion_destino
p5_12_6
Index(['ent', 'mun', 'descrip'], dtype='object')
entidad_destino
p5_12_7
Index(['cve', 'descrip'], dtype='object')
distrito_destino
dto_dest
Index(['cve', 'descrip'], dtype='object')
proposito
p5_13
Index(['cve', 'descrip'], dtype='object')
automovil
p5_14_01
Index(['cve', 'descrip'], dtype='object')
colectivo_micro
p5_14_02
Index(['cve', 'descrip'], dtype='object')
taxi_app
p5_14_03
Index(['cve', 'descrip'], dtype='object')
taxi
p5_14_04
Index(['cve', 'descrip'], dtype='object')
metro
p5_14_05
Index(['cve', 'descrip'], dtype='object')
autobus_rtp
p5_14_06
Index(['cve', 'descrip'], dtype='object')
bicicleta
p5_14_07
Index(['cve', 'descrip'], dtype='object')
autobus
p5_14_08
Index(['cve', 'descrip'], dtype='object')
moto
p5_14_09
Index(['cve', 'descrip'], dtype='object')
trolebus
p5_14_10
Index(['cve', 'descrip'], dtype='object')
metrobus_mexibus
p5_14_11
Index(['cve', 'descrip'], dtype='object')
tren_ligero
p5_14_12
Index(['cve', 'descrip'], dtype='object')
tren_suburbano
p5_14_13
Index(['cve', 'descrip'], dtype='object')
camino
p5_14_14
Index(['cve', 'descrip'], dtype='object')
mexicable
p5_14_15
Index(['cve', 'descrip'], dtype='object')
bicitaxi
p5_14_16
Index(['cve', 'descrip'], dtype='object')
mototaxi
p5_14_17
Index(['cve', 'descrip'], dtype='object')
transporte_escolar
p5_14_18
Index(['cve', 'descrip'], dtype='object')
transporte_personal
p5_14_19
Index(['cve', 'descrip'], dtype='object')
otro
p5_14_20
Index(['cve', 'descrip'], dtype='object')
condujo
p5_18
Index(['cve', 'descrip'], dtype='object')
lugar_estacionamiento
p5_20
Index(['cve', 'descrip'], dtype='object')
pago_estacionamiento
p5_22
Index(['cve', 'descrip'], dtype='object')
pago_usted
p5_24
Index(['cve', 'descrip'], dtype='object')
holograma_automovil
p5_25
Index(['cve', 'descrip'], dtype='object')
paradas_recoger_alguien
p5_27_1
Index(['cve', 'descrip'], dtype='object')
paradas_gasolinera
p5_27_2
Index(['cve', 'descrip'], dtype='object')
paradas_cajero
p5_27_3
Index(['cve', 'descrip'], dtype='object')
paradas_compra_rapida
p5_27_4
Index(['cve', 'descrip'], dtype='object')
paradas_convivencia_breve
p5_27_5
Index(['cve', 'descrip'], dtype='object')
paradas_descanso
p5_27_6
Index(['cve', 'descrip'], dtype='object')
paradas_tramite_rapido
p5_27_7
Index(['cve', 'descrip'], dtype='object')
paradas_otro_motivo
p5_27_8
Index(['cve', 'descrip'], dtype='object')
estrato_sociodemografico
estrato
Index(['cve', 'descrip'], dtype='object')
tamano_localidad
tloc
Index(['cve', 'descrip'], dtype='object')
sexo
sexo
Index(['cve', 'descrip'], dtype='object')

In [408]:
viajes.head()

,viaje_id,persona_id,num_viaje,delegacion_origen,hora_inicio,minuto_inicio,hora_termino,minuto_termino,delegacion_destino,automovil_num_veces,...,paradas_gasolinera,paradas_cajero,paradas_compra_rapida,paradas_convivencia_breve,paradas_descanso,paradas_tramite_rapido,paradas_otro_motivo,estrato_sociodemografico,tamano_localidad,sexo
0,2936,1268,1,15,8,0,9,0,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medio alto,"Localidades mayores de 100,000 habitantes",Mujer
1,2937,1268,2,16,14,0,15,30,15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medio alto,"Localidades mayores de 100,000 habitantes",Mujer
2,2938,1268,1,15,17,0,17,5,15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medio alto,"Localidades mayores de 100,000 habitantes",Mujer
3,2939,1268,2,15,23,0,23,5,15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medio alto,"Localidades mayores de 100,000 habitantes",Mujer
4,2940,1269,1,15,8,0,9,0,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medio alto,"Localidades mayores de 100,000 habitantes",Mujer

In [409]:
viajes.shape

(531594, 82)

In [411]:
viajes.to_csv("./data/viajes.csv")

PermissionError: [Errno 13] Permission denied: './data/viajes.csv'

## Coordenadas de distritos

In [1]:
import requests
import json
from config import API_KEY

In [23]:
distrito = "Condesa"

target_url = ('https://maps.googleapis.com/maps/api/geocode/json?address={0}, Mexico&key={1}').format(distrito, API_KEY)
print(target_url)
geo_data = requests.get(target_url).json()

https://maps.googleapis.com/maps/api/geocode/json?address=Condesa, Mexico&key=AIzaSyDxm3aYsWKpKzMNwbuvvf02389aCs7NuQc

In [24]:
geo_data

{'results': [{'address_components': [{'long_name': 'La Condesa',
     'short_name': 'La Condesa',
     'types': ['political', 'sublocality', 'sublocality_level_1']},
    {'long_name': 'Mexico City',
     'short_name': 'México D.F.',
     'types': ['locality', 'political']},
    {'long_name': 'Mexico City',
     'short_name': 'CDMX',
     'types': ['administrative_area_level_1', 'political']},
    {'long_name': 'Mexico',
     'short_name': 'MX',
     'types': ['country', 'political']}],
   'formatted_address': 'La Condesa, Mexico City, CDMX, Mexico',
   'geometry': {'bounds': {'northeast': {'lat': 19.4202262,
      'lng': -99.1700189},
     'southwest': {'lat': 19.4103954, 'lng': -99.18214929999999}},
    'location': {'lat': 19.4149803, 'lng': -99.17744619999999},
    'location_type': 'APPROXIMATE',
    'viewport': {'northeast': {'lat': 19.4202262, 'lng': -99.1700189},
     'southwest': {'lat': 19.4103954, 'lng': -99.18214929999999}}},
   'place_id': 'ChIJ4zXmiUT_0YUR57jJi24HHO0',
   'types': ['political', 'sublocality', 'sublocality_level_1']}],
 'status': 'OK'}

In [45]:
lat = geo_data["results"][0]["geometry"]["location"]["lat"]
lng = geo_data["results"][0]["geometry"]["location"]["lng"]

In [52]:
distritos = catalog_tviaje["dto_dest"]

In [53]:
for i in range(len(distritos)):
     
    distrito = distritos.loc[i,'descrip']
    
    target_url = ('https://maps.googleapis.com/maps/api/geocode/json?address={0}, CDMX&key={1}').format(distrito, API_KEY)
    geo_data = requests.get(target_url).json()
    
    distritos.loc[i,'lat'] = geo_data["results"][0]["geometry"]["location"]["lat"]
    distritos.loc[i,'lng'] = geo_data["results"][0]["geometry"]["location"]["lng"]

In [54]:
distritos.head(25)

    cve                  descrip        lat        lng
0   1    Centro Histórico         19.435707 -99.131757
1   2    Buenavista-Reforma       19.425938 -99.193705
2   3    Tlatelolco               19.452369 -99.138415
3   4    Morelos                  19.446823 -99.130396
4   5    Moctezuma                19.425186 -99.065316
5   6    Balbuena                 19.415772 -99.107331
6   6    Balbuena                 19.415772 -99.107331
7   7    Obrera                   19.415464 -99.138646
8   8    Condesa                  19.414980 -99.177446
9   8    Condesa                  19.414980 -99.177446
10  9    Napoles                  19.394357 -99.177446
11  9    Napoles                  19.394357 -99.177446
12  10   Vertiz Narvarte          19.380746 -99.155302
13  11   Reforma Iztaccihuatl     19.388595 -99.131088
14  11   Reforma Iztaccihuatl     19.388595 -99.131088
15  12   Palacio de los Deportes  19.405336 -99.099865
16  13   San Andrés Tetepilco     19.373162 -99.130396
17  13   San Andrés Tetepilco     19.373162 -99.130396
18  13   San Andrés Tetepilco     19.373162 -99.130396
19  14   Portales                 19.369241 -99.149766
20  15   Del Valle                19.381730 -99.164989
21  16   Chapultepec-Polanco      19.419481 -99.189456
22  17   Panteones                19.302331 -99.025752
23  17   Panteones                19.302331 -99.025752
24  18   Tezozomoc                19.489829 -99.197520

In [59]:
distritos = distritos.drop_duplicates()
distritos.shape

(196, 4)

In [62]:
distritos.to_csv("./data/coordenadas_distritos.csv")

In [3]:
distritos = pd.read_csv('./data/coordenadas_distritos.csv')
distritos.head()

   Unnamed: 0  cve             descrip        lat        lng
0           0    1    Centro Histórico  19.435707 -99.131757
1           1    2  Buenavista-Reforma  19.425938 -99.193705
2           2    3          Tlatelolco  19.452369 -99.138415
3           3    4             Morelos  19.446823 -99.130396
4           4    5           Moctezuma  19.425186 -99.065316

### Coordinates merging

In [20]:
viajes = pd.read_csv('./data/viajes1.csv')

In [9]:
viajes.head()

,Unnamed: 0,viaje_id,persona_id,dia_viaje,num_viaje,tipo_lugar_origen,delegacion_origen,entidad_origen,distrito_origen,lat_origen,...,paradas_descanso,paradas_tramite_rapido,paradas_otro_motivo,estrato_sociodemografico,factor,unidad_primaria_muestreo,estrato_diseno_muestral,tamano_localidad,sexo,edad
0,0,2936,1268,Viaje realizado entre semana (Sección V),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
1,1,2937,1268,Viaje realizado entre semana (Sección V),2,Oficina,16,Ciudad de México,Chapultepec-Polanco,19.419481,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
2,2,2938,1268,Viaje realizado en sábado (Sección VI),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
3,3,2939,1268,Viaje realizado en sábado (Sección VI),2,Otra vivienda,15,Ciudad de México,Buenavista-Reforma,19.425938,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
4,4,2940,1269,Viaje realizado entre semana (Sección V),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,22

In [6]:
viajes = viajes.merge(distritos, how='left', left_on='distrito_origen', right_on='descrip')
viajes = viajes.rename(columns={"lat":"lat_origen","lng":"lng_origen"})
viajes = viajes.drop(columns=['descrip', 'cve'])

In [25]:
viajes = viajes.merge(distritos, how='left', left_on='distrito_destino', right_on='descrip')
viajes = viajes.rename(columns={"lat":"lat_destino","lng":"lng_destino"})
viajes = viajes.drop(columns=['descrip', 'cve'])

In [24]:
viajes.shape

(531594, 84)

In [23]:
viajes = viajes.drop(columns=['Unnamed: 0','lat_destino','lat_destino.1'])

In [28]:
col_names=list(diccionario_tviaje['col_name'])

In [29]:
col_names.insert(8,'lat_origen')
col_names.insert(9,'lng_origen')
col_names.insert(18,'lat_destino')
col_names.insert(19,'lng_destino')
col_names

['viaje_id',
 'persona_id',
 'dia_viaje',
 'num_viaje',
 'tipo_lugar_origen',
 'delegacion_origen',
 'entidad_origen',
 'distrito_origen',
 'lat_origen',
 'lng_origen',
 'hora_inicio',
 'minuto_inicio',
 'hora_termino',
 'minuto_termino',
 'tipo_lugar_destino',
 'delegacion_destino',
 'entidad_destino',
 'distrito_destino',
 'lat_destino',
 'lng_destino',
 'proposito',
 'automovil',
 'automovil_num_veces',
 'colectivo_micro',
 'colectivo_micro_num_veces',
 'taxi_app',
 'taxi_app_num_veces',
 'taxi',
 'taxi_num_veces',
 'metro',
 'metro_num_veces',
 'autobus_rtp',
 'autobus_rtp_num_veces',
 'bicicleta',
 'bicicleta_num_veces',
 'autobus',
 'autobus_num_veces',
 'moto',
 'moto_num_veces',
 'trolebus',
 'trolebus_num_veces',
 'metrobus_mexibus',
 'metrobus_mexibus_num_veces',
 'tren_ligero',
 'tren_ligero_num_veces',
 'tren_suburbano',
 'tren_suburbano_num_veces',
 'camino',
 'camino_num_veces',
 'mexicable',
 'mexicable_num_veces',
 'bicitaxi',
 'bicitaxi_num_veces',
 'mototaxi',
 'mototaxi_num_veces',
 'transporte_escolar',
 'transporte_escolar_num_veces',
 'transporte_personal',
 'transporte_personal_num_veces',
 'otro',
 'otro_num_veces',
 'condujo',
 'personas_inicio_viaje',
 'lugar_estacionamiento',
 'horas_estacionamiento',
 'minutos_estacionamiento',
 'pago_estacionamiento',
 'pago_estacionamiento_cantidad',
 'pago_usted',
 'holograma_automovil',
 'num_paradas_10_min',
 'paradas_recoger_alguien',
 'paradas_gasolinera',
 'paradas_cajero',
 'paradas_compra_rapida',
 'paradas_convivencia_breve',
 'paradas_descanso',
 'paradas_tramite_rapido',
 'paradas_otro_motivo',
 'estrato_sociodemografico',
 'factor',
 'unidad_primaria_muestreo',
 'estrato_diseno_muestral',
 'tamano_localidad',
 'sexo',
 'edad']

In [30]:
viajes = viajes[col_names]

In [31]:
viajes.head()

,viaje_id,persona_id,dia_viaje,num_viaje,tipo_lugar_origen,delegacion_origen,entidad_origen,distrito_origen,lat_origen,lng_origen,...,paradas_descanso,paradas_tramite_rapido,paradas_otro_motivo,estrato_sociodemografico,factor,unidad_primaria_muestreo,estrato_diseno_muestral,tamano_localidad,sexo,edad
0,2936,1268,Viaje realizado entre semana (Sección V),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,-99.193705,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
1,2937,1268,Viaje realizado entre semana (Sección V),2,Oficina,16,Ciudad de México,Chapultepec-Polanco,19.419481,-99.189456,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
2,2938,1268,Viaje realizado en sábado (Sección VI),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,-99.193705,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
3,2939,1268,Viaje realizado en sábado (Sección VI),2,Otra vivienda,15,Ciudad de México,Buenavista-Reforma,19.425938,-99.193705,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,26
4,2940,1269,Viaje realizado entre semana (Sección V),1,Su hogar,15,Ciudad de México,Buenavista-Reforma,19.425938,-99.193705,...,NaN,NaN,NaN,Medio alto,244,87,40,"Localidades mayores de 100,000 habitantes",Mujer,22

In [32]:
viajes.to_csv("./data/viajes1.csv")

In [33]:
viajes.columns

Index(['viaje_id', 'persona_id', 'dia_viaje', 'num_viaje', 'tipo_lugar_origen',
       'delegacion_origen', 'entidad_origen', 'distrito_origen', 'lat_origen',
       'lng_origen', 'hora_inicio', 'minuto_inicio', 'hora_termino',
       'minuto_termino', 'tipo_lugar_destino', 'delegacion_destino',
       'entidad_destino', 'distrito_destino', 'lat_destino', 'lng_destino',
       'proposito', 'automovil', 'automovil_num_veces', 'colectivo_micro',
       'colectivo_micro_num_veces', 'taxi_app', 'taxi_app_num_veces', 'taxi',
       'taxi_num_veces', 'metro', 'metro_num_veces', 'autobus_rtp',
       'autobus_rtp_num_veces', 'bicicleta', 'bicicleta_num_veces', 'autobus',
       'autobus_num_veces', 'moto', 'moto_num_veces', 'trolebus',
       'trolebus_num_veces', 'metrobus_mexibus', 'metrobus_mexibus_num_veces',
       'tren_ligero', 'tren_ligero_num_veces', 'tren_suburbano',
       'tren_suburbano_num_veces', 'camino', 'camino_num_veces', 'mexicable',
       'mexicable_num_veces', 'bicitaxi', 'bicitaxi_num_veces', 'mototaxi',
       'mototaxi_num_veces', 'transporte_escolar',
       'transporte_escolar_num_veces', 'transporte_personal',
       'transporte_personal_num_veces', 'otro', 'otro_num_veces', 'condujo',
       'personas_inicio_viaje', 'lugar_estacionamiento',
       'horas_estacionamiento', 'minutos_estacionamiento',
       'pago_estacionamiento', 'pago_estacionamiento_cantidad', 'pago_usted',
       'holograma_automovil', 'num_paradas_10_min', 'paradas_recoger_alguien',
       'paradas_gasolinera', 'paradas_cajero', 'paradas_compra_rapida',
       'paradas_convivencia_breve', 'paradas_descanso',
       'paradas_tramite_rapido', 'paradas_otro_motivo',
       'estrato_sociodemografico', 'factor', 'unidad_primaria_muestreo',
       'estrato_diseno_muestral', 'tamano_localidad', 'sexo', 'edad'],
      dtype='object')

In [34]:
viajes.shape

(531594, 86)